language: php

php:
  - "7.1"

before_script:
  - cd CoreApi
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

services:
  - mysql

script:
  - vendor/bin/phpunit  