language: php

php:
  - "7.2"

cache:
  directories:
    - "./vendor"

dist: trusty

before_script:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - docker build -t siwecos-core-api .

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: develop
    script: >-
      docker tag siwecos-core-api siwecos/siwecos-core-api:develop &&
      docker push siwecos/siwecos-core-api:develop
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: >-
      docker tag siwecos-core-api siwecos/siwecos-core-api:latest &&
      docker push siwecos/siwecos-core-api:latest
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script: >-
      docker tag siwecos-core-api siwecos/siwecos-core-api:$TRAVIS_TAG &&
      docker push siwecos/siwecos-core-api:$TRAVIS_TAG
