swagger: "2.0"
info:
  version: "0.0.1"
  title: Siwecos Core Api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /scan/start:
    x-swagger-router-controller: scan
    post:
      description: Api endpoint for start scan (nameserver resolution in api call). All scans, defined in token are triggered. if dangerlevel is not defined, 0 is given.
      # used as the method name of the controller
      operationId: scanStart
      parameters:
      - in: body
        required: true
        name: scanStartRequest
        description: scanStartRequest
        schema: 
          $ref: '#/definitions/scanStartRequest'
              
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/scanStartResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /scan/status:
    x-swagger-router-controller: scan
    get:
      description: Get the actual state of give scan id
      # used as the method name of the controller
      operationId: scanStatus
      parameters:
      - in: query
        required: true
        name: scanId
        type: integer
              
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/scanStatusResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

# complex objects have schema definitions
definitions:
  scanStartRequest:
    type: object
    required:
    - domainName
    properties:
      domainName:
        type: string
      dangerLevel:
        type: integer
        minimum: 0
        maximum: 10
      callbackurls:
        type: array
        items:
          type: string
          
  
  
  scanStartResponse:
    properties:
      message:
        type: string
      scanId:
        type: integer
      

  scanStatusResponse:
    properties:
      statusMessage:
        type: string
      

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
